export enum ErrorCode {
	OK = "OK",
	UNKNOWN_ERROR = "UNKNOWN_ERROR",
	VALIDATION_ERROR = "VALIDATION_ERROR",

	ROLE_NOT_FOUND = "ROLE_NOT_FOUND",
	ACCOUNT_ALREADY_EXISTS = "ACCOUNT_ALREADY_EXISTS",
	INVALID_CREDENTIALS = "INVALID_CREDENTIALS",
}
