export enum ErrorCode {
	OK = "OK",
	UNKNOWN_ERROR = "UNKNOWN_ERROR",
	VALIDATION_ERROR = "VALIDATION_ERROR",

	ROLE_NOT_FOUND = "ROLE_NOT_FOUND",
	ACCOUNT_ALREADY_EXISTS = "ACCOUNT_ALREADY_EXISTS",
	INVALID_CREDENTIALS = "INVALID_CREDENTIALS",
	ACCOUNT_INACTIVE = "ACCOUNT_INACTIVE",
	PERMISSION_DENIED = "PERMISSION_DENIED",
	STAFF_ROLE_INACTIVE = "STAFF_ROLE_INACTIVE",
	STAFF_NOT_FOUND = "STAFF_NOT_FOUND",
	STAFF_ROLE_NOT_FOUND = "STAFF_ROLE_NOT_FOUND",
	STAFF_EMAIL_ALREADY_EXISTS = "STAFF_EMAIL_ALREADY_EXISTS",
	SELF_PROFILE_NOT_FOUND = "SELF_PROFILE_NOT_FOUND",
	HOYOLAB_CONFIG_MISSING = "HOYOLAB_CONFIG_MISSING",
	HOYOLAB_REQUEST_FAILED = "HOYOLAB_REQUEST_FAILED",
}
